runtime: python311 # or another supported version
instance_class: F1
service: backend
# entrypoint: gunicorn --bind 0.0.0.0:8080 tms.wsgi:application

automatic_scaling:
  max_idle_instances: automatic # default value
  min_pending_latency: 30ms # default value
  max_pending_latency: automatic

handlers:
  - url: .*
    script: auto
    secure: always
