# Generated by Django 5.1.3 on 2024-11-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=10, null=True)),
                ('longitude', models.CharField(max_length=10, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
