# Generated by Django 4.2.5 on 2023-09-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymembers',
            old_name='relations',
            new_name='relationship',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='primary_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='default_address',
            new_name='permanent_address',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='bill_book_no',
            new_name='receipt_book_no',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='bill_date',
            new_name='receipt_date',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='bill_no',
            new_name='receipt_no',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='village_name',
            new_name='village',
        ),
        migrations.AddField(
            model_name='familymembers',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='member_head_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='member_prefix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
