# Generated by Django 4.2.5 on 2023-09-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_relations_familymembers_relationship_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='people',
            unique_together={('name', 'mobile_number')},
        ),
    ]
