# Generated by Django 4.2.5 on 2023-09-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_people_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='member_registration_number',
            new_name='charity_registration_number',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='is_group_member',
            new_name='is_charity_member',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='area',
            new_name='taluk',
        ),
        migrations.AlterUniqueTogether(
            name='people',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='people',
            name='father_or_husband',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='is_card_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='member_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='people',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='receipt_book_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='people',
            name='receipt_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
