# Generated by Django 4.2.5 on 2023-09-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_member_registration_number_people_charity_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='id_card_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
