# Generated by Django 4.2.5 on 2023-09-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_people_id_card_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='member_head_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='member_prefix',
        ),
        migrations.AddField(
            model_name='familymembers',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
