# Generated by Django 4.2.5 on 2023-10-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_people_member_head_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='gender',
            field=models.CharField(default='ஆண்', max_length=10),
            preserve_default=False,
        ),
    ]
