# Generated by Django 4.2.5 on 2023-10-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_people_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='std_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
