# Generated by Django 4.2.5 on 2023-10-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_people_std_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='profile_image',
            field=models.JSONField(null=True),
        ),
    ]
