# Generated by Django 4.2.5 on 2023-10-31 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_people_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymembers',
            name='code',
        ),
        migrations.RemoveField(
            model_name='people',
            name='code',
        ),
    ]
