# Generated by Django 4.2.5 on 2023-11-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_familymembers_code_remove_people_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='trust_card_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
